// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiy9-PCegi_W2u7CAOqXCuS069IP5v8z4',
    appId: '1:516158430088:web:981aaa83b5d8dcead9783d',
    messagingSenderId: '516158430088',
    projectId: 'calorie-scanner-88a54',
    authDomain: 'calorie-scanner-88a54.firebaseapp.com',
    storageBucket: 'calorie-scanner-88a54.firebasestorage.app',
    measurementId: 'G-W5HPME37SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtmH7rb6vayFD-tW3Yuan9f_DtJIAK84c',
    appId: '1:516158430088:android:7c97f981d311261fd9783d',
    messagingSenderId: '516158430088',
    projectId: 'calorie-scanner-88a54',
    storageBucket: 'calorie-scanner-88a54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOk7TVmLdxWaUtnIf1qDil2hBxUYwR0LI',
    appId: '1:516158430088:ios:2fe43f00ec078a06d9783d',
    messagingSenderId: '516158430088',
    projectId: 'calorie-scanner-88a54',
    storageBucket: 'calorie-scanner-88a54.firebasestorage.app',
    iosBundleId: 'com.example.calorieScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOk7TVmLdxWaUtnIf1qDil2hBxUYwR0LI',
    appId: '1:516158430088:ios:2fe43f00ec078a06d9783d',
    messagingSenderId: '516158430088',
    projectId: 'calorie-scanner-88a54',
    storageBucket: 'calorie-scanner-88a54.firebasestorage.app',
    iosBundleId: 'com.example.calorieScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiy9-PCegi_W2u7CAOqXCuS069IP5v8z4',
    appId: '1:516158430088:web:da026be9c4891e11d9783d',
    messagingSenderId: '516158430088',
    projectId: 'calorie-scanner-88a54',
    authDomain: 'calorie-scanner-88a54.firebaseapp.com',
    storageBucket: 'calorie-scanner-88a54.firebasestorage.app',
    measurementId: 'G-EVWNCQKY17',
  );
}
